
all: 
	gcc client.c utils.c -o client
	gcc server_central.c -o server_central
	gcc server_horoscope.c -o server_horoscope
	gcc server_weather.c -o server_weather

clean:
	rm client server_central server_horoscope server_weather
